### DISCUSSION TITLE
Basic example using nornir_scrapli and Cisco Always-On Sandbox

### DISCUSSION THREAD

**Discussion by writememe** [scrapli/nornir_scrapli#137] [Show and tell]
# Overview

After a question in slack, I thought I'd make a very quick example so that people have something to work with..

Below is a cut-down basic example of using `nornir_scrapli` and the [Cisco Always-On IOS-XE Sandbox](https://devnetsandbox.cisco.com/RM/Diagram/Index/7b4d4209-a17c-4bc3-9b38-f15184e53a94?diagramType=Topology)

It performs the following:
- Connects to the sandbox host
- Runs a single command
- Prints output to screen

## File Structure

There are four files that you need to generate/copy into your local machine:

```bash
.
├── basic_nornir_scrapli_example.py
├── groups.yaml
├── hosts.yaml
└── requirements.txt
```

### `requirements.txt`

This file contains the python requirements to run this example. Ensure that they are on your machine/python virtual environment:

```text
nornir
nornir-scrapli
```

### `hosts.yaml`

This file contains the details for IOS-XE Sandbox host. In production, DO NOT save your passwords here in a clear-text, unencrypted file:

```yaml
---
sandbox-iosxe-latest-1.cisco.com:
    # NOTE: Bad practice in Production, don't do this.
    username: developer
    password: C1sco12345
    hostname: sandbox-iosxe-latest-1.cisco.com
    groups:
        - iosxe
 ```
 
 
### `groups.yaml`

This file contains a single group to setup the `iosxe` specific settings.

```yaml
---
iosxe:
    platform: ios
    # Setting scrapli connection options
    # https://github.com/carlmontanari/nornir_scrapli#a-simple-example
    connection_options:
        scrapli:
            platform: cisco_iosxe
            port: 22
            extras:
                auth_strict_key: false
 ```
 
 ### `basic_nornir_scrapli_example.py`
 
 Finally, here is the script which performs the tasks:
 
 ```python
 # Import modules
from nornir import InitNornir
import os
from nornir_scrapli.tasks import send_command
from nornir.core.task import Task
from nornir.core.task import Result

# Get path of the current dir under which the file is executed
dirname = os.path.dirname(os.path.abspath(__file__))


def get_nr():
    """
    Initialises a Nornir inventory using various configuration files.
    """
    # Initialise nornir
    nr = InitNornir(
        inventory={
            "options": {
                "host_file": os.path.join(
                    dirname,
                    "hosts.yaml",
                ),
                "group_file": os.path.join(
                    dirname,
                    "groups.yaml",
                ),
            }
        }
    )
    return nr


def scrapli_command_runner(task: Task, command: str = "show run") -> Result:
    """Run a single command on a host using Scrapli.

    Args:
        task: The nornir task object.
    """
    # Printout some diagnostic information
    print(f"Attempting command: '{command}' on host: '{task.host}' ...")
    # Run command using scrapli
    cmd_output = task.run(
        task=send_command, name=f"Execute Command: {command}", command=command
    )
    # Assign result of scrapli output and return
    result = Result(host=task.host, result=cmd_output.result)
    return result


# Initialise inventory
nr = get_nr()
# Specify command to run
command = "show run"
# Execute scrapli command runner on entire inventory
cmd_result = nr.run(task=scrapli_command_runner, command=command)
# Iterate over hosts and results and print them out
for host in cmd_result:
    # Printout some diagnostic information
    print(f"Host: '{host}' - Command: '{command}' result:")
    # Printout a seperator
    print("=" * 20)
    # Printout the results of the command output
    print(f"{cmd_result[host].result}")
    # Printout a seperator
    print("=" * 20)

 ```
 
 ## Ideas to extend the basic example
 
 Here are some ideas on how you can extend this to learn more about scrapli or nornir:
 - Save the outputs to a file
 - Write another function which takes a [list of commands](https://github.com/scrapli/nornir_scrapli/blob/main/nornir_scrapli/tasks/core/send_commands.py)
 - Run commands on other supported drivers
