### DISCUSSION TITLE
Genie Parser on Non Cisco Devices

### DISCUSSION THREAD

**Discussion by MrPaulAR** [scrapli/nornir_scrapli#71] [Q&A] [answered]
I'm working with some Juniper devices and I cannot get genie to parse the output.  I suspect the issue is related to genie not knowing which parser to use but I cannot see how to pass that info into nornir from the inventory yaml files.

I also believe that the reason it works with ios-xr devices is because the genie parser is defaulted to iosxe within scrapli.  I did just submit a pull request that was merged into scrapli dev branch but was still hoping there is a method to pass this into scrapli from nornir (inventory or after the fact).

**Comment by carlmontanari** [comment, marked as answer]
all "driver" arguments can be passed in via `extras` in inventory -- like [this](https://github.com/scrapli/nornir_scrapli/blob/master/examples/basic_netconf_usage/nornir_data/groups.yaml#L7-L9). so you can pass `genie_platform` there, or just install develop branch of scrapli now and that should basically do the same after your pr.

**Reply by MrPaulAR** [reply]
Perhaps I'm missing something but thanks for the pointers.

This is what I've got now in my groups.  I did use that as a template.
```
junos:
  platform: junos
  connection_options:
    scrapli:
      port: 22
      extras:
        ssh_config_file: True
        auth_strict_key: False
        transport: ssh2
```

I've also tried using juniper_junos as I've seen that somewhere over the past few days but I don't recall where exactly.

**Reply by carlmontanari** [reply]
Ah I get ya now I think!

So `extras` is just arguments that gets passed to the scrapli driver -- so anything you find [here](https://github.com/carlmontanari/scrapli/blob/master/scrapli/driver/core/juniper_junos/sync_driver.py#L53-L81)  can be put in there basically. the `platform` is a nornir specific thing (that we use in context of scrapli to make sure you end up using the right platform driver).

So something like this should do the trick:

```
junos:
  platform: junos
  connection_options:
    scrapli:
      port: 22
      extras:
        ssh_config_file: True
        auth_strict_key: False
        transport: ssh2
        genie_platform: junos
```

Hopefully that makes sense!

Carl
