### ISSUE TITLE
Scrapli-Netconf reports failed for non-failed tasks

### ISSUE THREAD

**Issue by dmulyalin** [scrapli/nornir_scrapli#108]
Hi,

Running in an issue where result returned by `netconf_get_config` task has `failed` attribute set to True even for seemingly fine output.

Files directory:
```
[root@test-host scrapli_netconf_test]# tree -A
.
├── config.yaml
├── hosts.yaml
└── test.py
```

 hosts.yaml:
```
iosxr1:
  hostname: sandbox-iosxr-1.cisco.com
  platform: cisco_iosxr
  username: admin
  password: C1sco12345
  connection_options:
    scrapli_netconf:
      port: 830
      extras:
        ssh_config_file: True
        auth_strict_key: False
        transport_options: 
          netconf_force_pty: False 
          
csr1000v-1:
  hostname: sandbox-iosxe-latest-1.cisco.com
  platform: cisco_ios
  username: developer
  password: C1sco12345
  port: 22
  connection_options:
    scrapli_netconf:
      port: 830
      extras:
        transport: paramiko
        ssh_config_file: True
        auth_strict_key: False
        transport_options: 
          netconf_force_pty: False
```

config.yaml:
```
inventory:
  plugin: SimpleInventory
  options:
    host_file: "hosts.yaml"
        
runner:
  plugin: threaded
  options:
    num_workers: 5
```

test.py - contains copied `netconf_get_config` task but with some print statements:
```
from nornir import InitNornir
from typing import List, Optional, Union
from nornir.core.task import Result, Task
from nornir_scrapli.result import ScrapliResult, process_command_result

nr = InitNornir(config_file="config.yaml")


def netconf_get_config(
    task: Task,
    source: str = "running",
    filter_: Optional[Union[str, List[str]]] = None,
    filter_type: str = "subtree",
) -> Result:
    """
    Get config from the device with scrapli_netconf
    Args:
        task: nornir task object
        source: configuration source to get; typically one of running|startup|candidate
        filter_: string of filter(s) to apply to configuration
        filter_type: type of filter; subtree|xpath
    Returns:
        Result: nornir result object with Result.result value set the string result of the
            get_config operation
    Raises:
        N/A
    """
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
    scrapli_response = scrapli_conn.get_config(
        source=source, filter_=filter_, filter_type=filter_type
    )
    
    print("!!!!!! task.host.name: ", task.host.name)
    print("!!!!!! scrapli_response.error_messages ", scrapli_response.error_messages)
    print("!!!!!! scrapli_response.failed ", scrapli_response.failed)
    print("!!!!!! scrapli_response.failed_when_contains ", scrapli_response.failed_when_contains)
    
    is_contains_err = any(err in scrapli_response.raw_result for err in scrapli_response.failed_when_contains)
    print("!!!!!! is_contains_err: ", is_contains_err)
    
    result = ScrapliResult(
        host=task.host,
        result=process_command_result(scrapli_response=scrapli_response),
        scrapli_response=scrapli_response,
        changed=False,
    )
    return result

result = nr.run(task=netconf_get_config)

print("!!!!!!!!!!!!!!!! result['iosxr1'].failed", result["iosxr1"].failed)
print("!!!!!!!!!!!!!!!! result['csr1000v-1'].failed", result["iosxr1"].failed)


print("!!!!!!!!!!!!!!!! result['iosxr1'].result", result["iosxr1"].result[:50])
print("!!!!!!!!!!!!!!!! result['csr1000v-1'].result", result["iosxr1"].result[:50])
```

Running above test.py file prints this to the screen:
```
[root@salt-minion-nrp1 scrapli_netconf_test]# python3 test.py 
!!!!!! task.host.name:  csr1000v-1
!!!!!! scrapli_response.error_messages  []
!!!!!! scrapli_response.failed  False
!!!!!! scrapli_response.failed_when_contains  [b'</rpc-error>', b'</rpc-errors>', b'<rpc-error>', b'<rpc-errors>']
!!!!!! is_contains_err:  False

!!!!!! task.host.name:  iosxr1
!!!!!! scrapli_response.error_messages  []
!!!!!! scrapli_response.failed  True
!!!!!! scrapli_response.failed_when_contains  [b'</rpc-error>', b'</rpc-errors>', b'<rpc-error>', b'<rpc-errors>']
!!!!!! is_contains_err:  False

!!!!!!!!!!!!!!!! result['iosxr1'].failed True
!!!!!!!!!!!!!!!! result['csr1000v-1'].failed True

!!!!!!!!!!!!!!!! result['iosxr1'].result <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:b
!!!!!!!!!!!!!!!! result['csr1000v-1'].result <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:b
```

As you can see task result for both hosts have `failed` set to true, even though for `csr1000v-1` host `scrapli_response.failed`  is False and even more strange for `iosxr1` host, where `scrapli_response.failed` is True, but xml output from devices does not contain any of `failed_when_contains ` patterns and `scrapli_response.error_messages` is empty.

OS: CenttOS7
Python: Python 3.6.8
Versions tried:
```
[root@test-host scrapli_netconf_test]#   python3 -m pip list | grep -E "nornir|scrapli|lxml"
lxml                         4.8.0
nornir                       3.2.0
nornir-scrapli               2022.1.30a1
nornir-utils                 0.1.2
scrapli                      2021.7.30
scrapli-cfg                  2021.7.30
scrapli-community            2021.7.30
scrapli-netconf              2022.1.30a1
```
and
```
[root@test-host scrapli_netconf_test]#   python3 -m pip list | grep -E "nornir|scrapli|lxml"
lxml                         4.8.0
nornir                       3.2.0
nornir-scrapli               2021.7.30
nornir-utils                 0.1.2
scrapli                      2021.7.30
scrapli-cfg                  2021.7.30
scrapli-community            2021.7.30
scrapli-netconf              2021.7.30
```

Not sure if something wrong with my environment or am I doing something wrong.
