### ISSUE TITLE
scrapli_channel.log is empty

### ISSUE THREAD

**Issue by gbieli** [scrapli/nornir_scrapli#122]
Hi,

I've seen that you can specify a channel_log with scrapli. I tried that with nornir_scrapli, but my log file remains empty. Below are my settings and the task code. Any ideas what could be wrong or is this not supported with nornir?

defaults.yaml:
```
---
platform: ios
connection_options:
 scrapli:
  platform: cisco_iosxe
  port: 22
  extras:
   channel_log: True
   channel_log_mode: append
   ssh_config_file: True
   auth_strict_key: False
 scrapli_netconf:
  port: 830
  extras:
   ssh_config_file: True
   auth_strict_key: False
```

code snippet:
```
s_100 = nr.filter(name="s-100")
    command_results = s_100.run(name="print version", task=send_command, command="show version | i RELEASE")
    print_result(command_results)
```

libraries:
```
nornir-scrapli==2022.1.30
scrapli==2022.1.30.post1
scrapli-cfg==2022.1.30
scrapli-community==2022.1.30
scrapli-netconf==2022.1.30
```

Regards,
Gérard
