### ISSUE TITLE
Help with handling ssh exceptions nornir-scarply

### ISSUE THREAD

**Issue by srqjan** [scrapli/nornir_scrapli#56]
Hi , 

I am getting an error with dealing with device:
"scrapli.exceptions.ScrapliAuthenticationFailed: No matching key exchange found for host, their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"

How can I include scarpli "transport_options" in to nornir-scarpli? 

BR

**Comment by carlmontanari** [comment]
Something like:

```
---
iosxe:
  platform: ios
  connection_options:
    scrapli:
      platform: cisco_iosxe
      extras:
        auth_strict_key: False
        transport: system
        transport_options: {"open_cmd": ["-o", "KexAlgorithms=+diffie-hellman-group1-sha1"]}
```

Or just use ssh_config_file w/ a path or True and set up appropriate kex in there.

I'm going to close this now. For things that are not bugs or discussions on feature adds/changes or if you still need help please use slack or discussions.

Carl
