### ISSUE TITLE
How to disable console logging

### ISSUE THREAD

**Issue by xiaopeng163** [scrapli/nornir_scrapli#57]
hi @carlmontanari ,I tried to find a way to disable console logging, but couldn't find it, the program always print out the output to console.

my code is very simple, just a task to execute cisco show command, but it always print the show output to console.

```
from nornir_scrapli.tasks import send_commands
from nornir.core.task import Task, Result


def show_collector(task: Task, cmd_list)-> Result:

    """execute show command and return the output as string
    """
    output = task.run(
        task=send_commands,
        commands=cmd_list)
    return Result(
        host=task.host,
        result=output.result
    )

 nr = InitNornir(config_file="config.yml")
 nr = nr.filter(F(groups__contains="ios"))
 nornir_set_creds(nr, ssh_username, ssh_password)
 cmd_list = [
        "show ip nat statistics",
        "show ip nat translations"
    ]
result = nr.run(task=show_collector, cmd_list=cmd_list)
```

my config file

```
---
inventory:
  plugin: YAMLInventory
  options:
    host_file: "inventory/hosts.yml"
    group_file: "inventory/groups.yml"
    defaults_file: "inventory/defaults.yml"
runner:
  plugin: threaded
  options:
    num_workers: 100
```

Thanks,

Regards,

Peng
